### ISSUE TITLE
Please include www.zinzy.website

### ISSUE THREAD

**Issue by zinzy** [nkoehring/250kb-club#107]
Hey there, I'd love to have my website included in your list!

https://gtmetrix.com/reports/www.zinzy.website/7eV6SaUh/

**Comment by nkoehring** [comment]
Hi! I'm adding your page but I highly suggest you to fix that `www`. Your page currently only works with www subdomain while [zinzy.website](https://zinzy.website) ends up on the bhosted landing page.
On a side note: you might also want to fix the URL you have in your Github profile.
Otherwise: Nice work with the queer catholic community. I'm really not at all religious but I'm happy about any movement that fights for personal freedom, whichever type.
