### ISSUE TITLE
Add https://hytracer.ink

### ISSUE THREAD

**Issue by hytracer** [nkoehring/250kb-club#341]
Hi!! I was wondering if my website could get added to the list

https://gtmetrix.com/reports/hytracer.ink/Pak6iMl1/

**Comment by nkoehring** [comment]
Welcome to the 250kb Club! Your page will be https://250kb.club/hytracer-ink/

**Comment by nkoehring** [comment]
Sorry, but adding your site didn't work. There is some spotify stuff loading and it weighs megabytes:
https://yellowlab.tools/result/gmuv3ya65o/rule/totalWeight

**Comment by hytracer** [comment]
Hello! I fixed the issue, it should be okay now

**Comment by nkoehring** [comment]
The issue is fixed and your page is welcomed back to the 250KB Club!

**Comment by nkoehring** [comment]
Hi @hytracer ! Unfortunately, your page grew a lot, because you added a beautiful, but way too large background image. I suggest using this much more feasible version instead:

![hytracer](https://github.com/nkoehring/250kb-club/assets/246402/2a654e14-3c9d-4f9c-b4ee-79df913c7e26)

There are also lots of other pictures, that are only tiny on your page, but load large versions of the images (see screenshot):
![scrot-20240108220515](https://github.com/nkoehring/250kb-club/assets/246402/fdda4ad1-0236-4c85-8da7-4adef77b708f)

As well as you avatar picture, where I suggest this one instead:
![hytracer_avatar](https://github.com/nkoehring/250kb-club/assets/246402/a624f275-644e-4205-8bbc-ce84de55a6a1)
