### ISSUE TITLE
Add https://willhackett.com

### ISSUE THREAD

**Issue by willhackett** [nkoehring/250kb-club#344]

**Comment by nkoehring** [comment]
Nice and simple page, but pretty large for what it does. Not too large though, so welcome to the 250kb Club!

One question regarding your analytics: I saw you are using Umami, which I never heard of before. Is it any good? I use goatcounter for most of my pages, but get (rather unexplainable) CSP issues since a while. Maybe selfhosting something lightweight would be a good solution.
